language: csharp
solution: Colina.sln

mono:
  - latest
dotnet: 1.0.0-preview2-003121

matrix:
  include:
    - dotnet: 1.0.0-preview2-003121
      mono: none
      env: DOTNETCORE=1
    - mono: latest
    
script:  
  - ./build.sh